version: '3'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      #      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  rest-service:
    build:
      context: ./rest-service/
      args:
        JAR_FILE: rest-service-1.0-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      KAFKA_HOST: kafka
    depends_on:
      - kafka

  consumer-1:
    build:
      context: ./consumer-1
      args:
        JAR_FILE: consumer-1-1.0-SNAPSHOT.jar
    environment:
      KAFKA_HOST: kafka
    depends_on:
      - rest-service

  consumer-2:
    build:
      context: ./consumer-2
      args:
        JAR_FILE: consumer-2-1.0-SNAPSHOT.jar
    environment:
      KAFKA_HOST: kafka
    depends_on:
      - rest-service